        !COMPILER-GENERATED INTERFACE MODULE: Fri Mar 25 19:39:29 2022
        MODULE COUNT__genmod
          INTERFACE 
            SUBROUTINE COUNT
            END SUBROUTINE COUNT
          END INTERFACE 
        END MODULE COUNT__genmod
